PsycoTest/Controllers/ManagerTestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PsycoTest.Controllers
{
    public class ManagerTestsController : Controller
    {
        // GET: ManagerTests
        public ActionResult WorkTests()
        {
            return View();
        }
    }
}

PsycoTest/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PsycoTest.Controllers
{
    public class TestsController : Controller
    {
        DBModel.ModelDBPsycoTest dBPsyco = new DBModel.ModelDBPsycoTest();

        public ActionResult ListTest()
        {
            List<DBModel.Test> dBModel = new List<DBModel.Test>();
            dBModel = dBPsyco.Test.ToList();
            return View(dBModel.ToList());
        }


        public ActionResult Test(int id = 0)
        {
            DBModel.Test test = dBPsyco.Test.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }
    }
}

PsycoTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-navbar border-bottom box-shadow mb-3">
            <img src="/Resources/feather.png" style="width: 80px; height: 50px" />
            <div class="container">
                @Html.ActionLink("PsycoTest", "Index", "Home", null, new { @style = "color: blue; font-size: 32pt; font-family: Times New Roman; font-weight:600;", @class="nav-link" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Переключить навигацию" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" style="display: flex; justify-content: center">
                    @Html.Partial("_PartialNavigation")
                </div>
            </div>
            <div style="display: flex; justify-content: center ">
                @Html.Partial("_PartialLogin")
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-navbar" style="position: absolute; bottom: 0; width: 100%; white-space: nowrap; line-height: 60px;">
        <div class="container">
           &copy; @DateTime.Now.Year - PsycoTest
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PsycoTest/Views/Shared/_PartialLogin.cshtml
@if (Session["UserLogin"] == null)
{
    <ul class="navbar-nav" style="font-size: 20px;">
        <li class="nav-item"> @Html.ActionLink("Регистрация", "Register", "Account", new { area = "" }, new { @class = "nav-link" })</li>
        <li class="nav-item"> @Html.ActionLink("Вход", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
    </ul>
}
else
{
    <ul class="navbar-nav" style="font-size: 20px; display: flex; justify-content: center; justify-items: center">
        <li class="nav-item"> @Html.Label(Session["UserLastName"] + " " + Session["UserFirstName"] + " " + Session["UserPatronymic"])</li>
        <li class="nav-item"> @Html.ActionLink("Выход", "Logout", "Account", new { area = "" }, new {@class = "nav-link" })</li>
    </ul>
}

PsycoTest/Views/Shared/_PartialNavigation.cshtml
@if (Session["UserLogin"] == null)
{
    <ul class="navbar-nav flex-grow-1" style="font-size: 20px; text-align: center;  display: flex; justify-content: center ">
        <li style="width: 200px;" class="backnav">@Html.ActionLink("Главная страница", "Index", "Home", new { area = "" }, new { @style = "color: white;", @class = "nav-link", })</li>
        <li style="margin-left: 50px; width: 200px" class="backnav">@Html.ActionLink("Тесты", "ListTest", "Tests", new { area = "" }, new { @style = "color: white;", @class = "nav-link" })</li>
    </ul>
}
else
{
    if (Session["UserLogin"].ToString().Contains("Admin"))
    {
        <ul class="navbar-nav flex-grow-1" style="font-size: 20px; text-align: center; position: relative; left: -40px; display: flex; justify-content: center ">
            <li style="margin-left: 110px;width: 200px;" class="backnav">@Html.ActionLink("Главная страница", "Index", "Home", new { area = "" }, new { @style = "color: white;", @class = "nav-link" })</li>
            <li style="margin-left: 50px; width: 200px" class="backnav">@Html.ActionLink("Тесты", "ListTest", "Tests", new { area = "" }, new { @style = "color: white;", @class = "nav-link" })</li>
            <li style="margin-left: 50px; width: 200px" class="backnav">@Html.ActionLink("Работа с тестами", "WorkTests", "ManagerTests", new { area = "" }, new { @style = "color: white", @class = "nav-link" })</li>
            <li style="margin-left: 50px; width: 200px" class="backnav">@Html.ActionLink("Пользователи", "Users", "Admin", new { area = "" }, new { @style = "color: white", @class = "nav-link" })</li>
        </ul>
    }
    else
    {
        <ul class="navbar-nav flex-grow-1" style="font-size: 20px; text-align: center;  display: flex; justify-content: center ">
            <li style="width: 200px;" class="backnav">
                @Html.ActionLink("Главная страница", "Index", "Home", new { area = "" }, new { @style = "color: white;", @class = "nav-link" })
            </li>
            <li style="margin-left: 50px; width: 200px" class="backnav">@Html.ActionLink("Тесты", "ListTest", "Tests", new { area = "" }, new { @style = "color: white;", @class = "nav-link" })</li>
            <li style="margin-left: 50px; width: 200px" class="backnav"> @Html.ActionLink("Профиль", "UserProfile", "User", new {id = Session["UserId"] }, new { @style = "color: white;", @class = "nav-link" }) </li>
        </ul>

    }
}


<style>
        .backnav {
            background-color: #42aaff;
            border-radius: 4px;
        }

            .backnav:hover {
                background-color: #24afb1;
            }

</style>